# Generated by Django 5.1.1 on 2026-01-27 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0015_hardware_abbreviation'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='article_nom',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Артикул изделия'),
        ),
    ]
