# Generated by Django 5.1.1 on 2026-01-28 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0016_component_article_nom'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecoveryMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Метод восстановления')),
                ('abbreviation', models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Аббревиатура')),
            ],
            options={
                'verbose_name': 'Метод восстановления',
                'verbose_name_plural': 'Методы восстановления',
                'ordering': ('abbreviation',),
            },
        ),
    ]
