# Generated by Django 5.1.1 on 2026-01-28 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0017_recoverymethod'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='appointment',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Назначение'),
        ),
        migrations.AddField(
            model_name='part',
            name='recovery_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parts', to='hardware.recoverymethod', verbose_name='Метод восстановления'),
        ),
    ]
