# Generated by Django 5.1.1 on 2026-01-28 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0018_part_appointment_part_recovery_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='appointment',
        ),
    ]
