# Generated by Django 5.1.1 on 2026-01-28 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0019_remove_part_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='recovery_method',
        ),
        migrations.AddField(
            model_name='component',
            name='recovery_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parts', to='hardware.recoverymethod', verbose_name='Метод восстановления'),
        ),
    ]
