# Generated by Django 5.1.1 on 2026-01-28 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0020_remove_part_recovery_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='appointment',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Функция'),
        ),
    ]
