# Generated by Django 5.1.1 on 2026-01-28 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0021_component_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabinet',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Местоположение'),
        ),
    ]
