# Generated by Django 5.1.1 on 2026-01-28 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0022_cabinet_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabinet',
            name='name_ptc',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Наименование ПТК'),
        ),
    ]
